const DEFAULT_SPRITES = [
  {
    "id": 1,
    "name": "Water Sprite",
    "rarity": "RARE",
    "image": "assets/sprite_01.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Water",
    "category": "official-sheet",
    "sortGroup": 0,
    "fallbackImage": "assets/sprite_01.png",
    "notes": ""
  },
  {
    "id": 2,
    "name": "Gold Water Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_02.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Water",
    "category": "official-sheet",
    "sortGroup": 0,
    "fallbackImage": "assets/sprite_02.png",
    "notes": ""
  },
  {
    "id": 3,
    "name": "Gummy Water Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_03.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gummy",
    "baseName": "Water",
    "category": "official-sheet",
    "sortGroup": 0,
    "fallbackImage": "assets/sprite_03.png",
    "notes": ""
  },
  {
    "id": 4,
    "name": "Galaxy Water Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_04.png",
    "level": 2,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Galaxy",
    "baseName": "Water",
    "category": "official-sheet",
    "sortGroup": 0,
    "fallbackImage": "assets/sprite_04.png",
    "notes": ""
  },
  {
    "id": 62,
    "name": "Holofoil Water Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_01.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Water",
    "category": "holofoil-gem-tracker",
    "sortGroup": 0,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Water_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_01.png",
    "notes": ""
  },
  {
    "id": 78,
    "name": "Gem Water Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_01.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Water",
    "category": "holofoil-gem-tracker",
    "sortGroup": 0,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Water_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_01.png",
    "notes": ""
  },
  {
    "id": 5,
    "name": "Earth Sprite",
    "rarity": "RARE",
    "image": "assets/sprite_05.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Earth",
    "category": "official-sheet",
    "sortGroup": 1,
    "fallbackImage": "assets/sprite_05.png",
    "notes": ""
  },
  {
    "id": 6,
    "name": "Gold Earth Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_06.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Earth",
    "category": "official-sheet",
    "sortGroup": 1,
    "fallbackImage": "assets/sprite_06.png",
    "notes": ""
  },
  {
    "id": 7,
    "name": "Gummy Earth Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_07.png",
    "level": 3,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gummy",
    "baseName": "Earth",
    "category": "official-sheet",
    "sortGroup": 1,
    "fallbackImage": "assets/sprite_07.png",
    "notes": ""
  },
  {
    "id": 8,
    "name": "Galaxy Earth Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_08.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Galaxy",
    "baseName": "Earth",
    "category": "official-sheet",
    "sortGroup": 1,
    "fallbackImage": "assets/sprite_08.png",
    "notes": ""
  },
  {
    "id": 63,
    "name": "Holofoil Earth Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_05.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Earth",
    "category": "holofoil-gem-tracker",
    "sortGroup": 1,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Earth_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_05.png",
    "notes": ""
  },
  {
    "id": 79,
    "name": "Gem Earth Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_05.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Earth",
    "category": "holofoil-gem-tracker",
    "sortGroup": 1,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Earth_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_05.png",
    "notes": ""
  },
  {
    "id": 9,
    "name": "Fire Sprite",
    "rarity": "RARE",
    "image": "assets/sprite_09.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Fire",
    "category": "official-sheet",
    "sortGroup": 2,
    "fallbackImage": "assets/sprite_09.png",
    "notes": ""
  },
  {
    "id": 10,
    "name": "Gold Fire Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_10.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Fire",
    "category": "official-sheet",
    "sortGroup": 2,
    "fallbackImage": "assets/sprite_10.png",
    "notes": ""
  },
  {
    "id": 11,
    "name": "Gummy Fire Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_11.png",
    "level": 3,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Fire",
    "category": "official-sheet",
    "sortGroup": 2,
    "fallbackImage": "assets/sprite_11.png",
    "notes": ""
  },
  {
    "id": 12,
    "name": "Galaxy Fire Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_12.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Galaxy",
    "baseName": "Fire",
    "category": "official-sheet",
    "sortGroup": 2,
    "fallbackImage": "assets/sprite_12.png",
    "notes": ""
  },
  {
    "id": 64,
    "name": "Holofoil Fire Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_09.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Fire",
    "category": "holofoil-gem-tracker",
    "sortGroup": 2,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Fire_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_09.png",
    "notes": ""
  },
  {
    "id": 80,
    "name": "Gem Fire Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_09.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Fire",
    "category": "holofoil-gem-tracker",
    "sortGroup": 2,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Fire_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_09.png",
    "notes": ""
  },
  {
    "id": 13,
    "name": "Duck Sprite",
    "rarity": "EPIC",
    "image": "assets/sprite_13.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Duck",
    "category": "official-sheet",
    "sortGroup": 3,
    "fallbackImage": "assets/sprite_13.png",
    "notes": ""
  },
  {
    "id": 14,
    "name": "Gold Duck Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_14.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Duck",
    "category": "official-sheet",
    "sortGroup": 3,
    "fallbackImage": "assets/sprite_14.png",
    "notes": ""
  },
  {
    "id": 15,
    "name": "Gummy Duck Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_15.png",
    "level": 1,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Duck",
    "category": "official-sheet",
    "sortGroup": 3,
    "fallbackImage": "assets/sprite_15.png",
    "notes": ""
  },
  {
    "id": 16,
    "name": "Galaxy Duck Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_16.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Duck",
    "category": "official-sheet",
    "sortGroup": 3,
    "fallbackImage": "assets/sprite_16.png",
    "notes": ""
  },
  {
    "id": 65,
    "name": "Holofoil Duck Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_13.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Duck",
    "category": "holofoil-gem-tracker",
    "sortGroup": 3,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Duck_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_13.png",
    "notes": ""
  },
  {
    "id": 81,
    "name": "Gem Duck Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_13.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Duck",
    "category": "holofoil-gem-tracker",
    "sortGroup": 3,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Duck_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_13.png",
    "notes": ""
  },
  {
    "id": 17,
    "name": "Ghost Sprite",
    "rarity": "EPIC",
    "image": "assets/sprite_17.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Ghost",
    "category": "official-sheet",
    "sortGroup": 4,
    "fallbackImage": "assets/sprite_17.png",
    "notes": ""
  },
  {
    "id": 18,
    "name": "Gold Ghost Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_18.png",
    "level": 4,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Ghost",
    "category": "official-sheet",
    "sortGroup": 4,
    "fallbackImage": "assets/sprite_18.png",
    "notes": ""
  },
  {
    "id": 19,
    "name": "Gummy Ghost Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_19.png",
    "level": 2,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Ghost",
    "category": "official-sheet",
    "sortGroup": 4,
    "fallbackImage": "assets/sprite_19.png",
    "notes": ""
  },
  {
    "id": 20,
    "name": "Galaxy Ghost Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_20.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Ghost",
    "category": "official-sheet",
    "sortGroup": 4,
    "fallbackImage": "assets/sprite_20.png",
    "notes": ""
  },
  {
    "id": 66,
    "name": "Holofoil Ghost Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_17.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Ghost",
    "category": "holofoil-gem-tracker",
    "sortGroup": 4,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Ghost_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_17.png",
    "notes": ""
  },
  {
    "id": 82,
    "name": "Gem Ghost Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_17.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Ghost",
    "category": "holofoil-gem-tracker",
    "sortGroup": 4,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Ghost_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_17.png",
    "notes": ""
  },
  {
    "id": 21,
    "name": "Dream Sprite",
    "rarity": "LEGENDARY",
    "image": "assets/sprite_21.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Dream",
    "category": "official-sheet",
    "sortGroup": 5,
    "fallbackImage": "assets/sprite_21.png",
    "notes": ""
  },
  {
    "id": 22,
    "name": "Gold Dream Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_22.png",
    "level": 1,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gold",
    "baseName": "Dream",
    "category": "official-sheet",
    "sortGroup": 5,
    "fallbackImage": "assets/sprite_22.png",
    "notes": ""
  },
  {
    "id": 23,
    "name": "Gummy Dream Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_23.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gummy",
    "baseName": "Dream",
    "category": "official-sheet",
    "sortGroup": 5,
    "fallbackImage": "assets/sprite_23.png",
    "notes": ""
  },
  {
    "id": 24,
    "name": "Galaxy Dream Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_24.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Dream",
    "category": "official-sheet",
    "sortGroup": 5,
    "fallbackImage": "assets/sprite_24.png",
    "notes": ""
  },
  {
    "id": 67,
    "name": "Holofoil Dream Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_21.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Dream",
    "category": "holofoil-gem-tracker",
    "sortGroup": 5,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Dream_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_21.png",
    "notes": ""
  },
  {
    "id": 83,
    "name": "Gem Dream Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_21.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Dream",
    "category": "holofoil-gem-tracker",
    "sortGroup": 5,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Dream_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_21.png",
    "notes": ""
  },
  {
    "id": 25,
    "name": "Demon Sprite",
    "rarity": "EPIC",
    "image": "assets/sprite_25.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Demon",
    "category": "official-sheet",
    "sortGroup": 6,
    "fallbackImage": "assets/sprite_25.png",
    "notes": ""
  },
  {
    "id": 26,
    "name": "Gold Demon Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_26.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Demon",
    "category": "official-sheet",
    "sortGroup": 6,
    "fallbackImage": "assets/sprite_26.png",
    "notes": ""
  },
  {
    "id": 27,
    "name": "Gummy Demon Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_27.png",
    "level": 1,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Demon",
    "category": "official-sheet",
    "sortGroup": 6,
    "fallbackImage": "assets/sprite_27.png",
    "notes": ""
  },
  {
    "id": 28,
    "name": "Galaxy Demon Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_28.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Galaxy",
    "baseName": "Demon",
    "category": "official-sheet",
    "sortGroup": 6,
    "fallbackImage": "assets/sprite_28.png",
    "notes": ""
  },
  {
    "id": 68,
    "name": "Holofoil Demon Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_25.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Demon",
    "category": "holofoil-gem-tracker",
    "sortGroup": 6,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Demon_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_25.png",
    "notes": ""
  },
  {
    "id": 84,
    "name": "Gem Demon Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_25.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Demon",
    "category": "holofoil-gem-tracker",
    "sortGroup": 6,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Demon_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_25.png",
    "notes": ""
  },
  {
    "id": 29,
    "name": "Punk Sprite",
    "rarity": "LEGENDARY",
    "image": "assets/sprite_29.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Punk",
    "category": "official-sheet",
    "sortGroup": 7,
    "fallbackImage": "assets/sprite_29.png",
    "notes": ""
  },
  {
    "id": 30,
    "name": "Gold Punk Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_30.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Punk",
    "category": "official-sheet",
    "sortGroup": 7,
    "fallbackImage": "assets/sprite_30.png",
    "notes": ""
  },
  {
    "id": 31,
    "name": "Gummy Punk Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_31.png",
    "level": 5,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Punk",
    "category": "official-sheet",
    "sortGroup": 7,
    "fallbackImage": "assets/sprite_31.png",
    "notes": ""
  },
  {
    "id": 32,
    "name": "Galaxy Punk Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_32.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Galaxy",
    "baseName": "Punk",
    "category": "official-sheet",
    "sortGroup": 7,
    "fallbackImage": "assets/sprite_32.png",
    "notes": ""
  },
  {
    "id": 69,
    "name": "Holofoil Punk Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_29.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Punk",
    "category": "holofoil-gem-tracker",
    "sortGroup": 7,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Punk_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_29.png",
    "notes": ""
  },
  {
    "id": 85,
    "name": "Gem Punk Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_29.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Punk",
    "category": "holofoil-gem-tracker",
    "sortGroup": 7,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Punk_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_29.png",
    "notes": ""
  },
  {
    "id": 33,
    "name": "King Sprite",
    "rarity": "EPIC",
    "image": "assets/sprite_33.png",
    "level": 4,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "King",
    "category": "official-sheet",
    "sortGroup": 8,
    "fallbackImage": "assets/sprite_33.png",
    "notes": ""
  },
  {
    "id": 34,
    "name": "Gold King Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_34.png",
    "level": 4,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "King",
    "category": "official-sheet",
    "sortGroup": 8,
    "fallbackImage": "assets/sprite_34.png",
    "notes": ""
  },
  {
    "id": 35,
    "name": "Gummy King Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_35.png",
    "level": 1,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "King",
    "category": "official-sheet",
    "sortGroup": 8,
    "fallbackImage": "assets/sprite_35.png",
    "notes": ""
  },
  {
    "id": 36,
    "name": "Galaxy King Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_36.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "King",
    "category": "official-sheet",
    "sortGroup": 8,
    "fallbackImage": "assets/sprite_36.png",
    "notes": ""
  },
  {
    "id": 70,
    "name": "Holofoil King Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_33.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "King",
    "category": "holofoil-gem-tracker",
    "sortGroup": 8,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_King_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_33.png",
    "notes": ""
  },
  {
    "id": 86,
    "name": "Gem King Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_33.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "King",
    "category": "holofoil-gem-tracker",
    "sortGroup": 8,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_King_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_33.png",
    "notes": ""
  },
  {
    "id": 37,
    "name": "Burnt Peanut",
    "rarity": "MYTHIC",
    "image": "assets/sprite_37.png",
    "level": 4,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Burnt Peanut",
    "category": "official-sheet",
    "sortGroup": 9,
    "fallbackImage": "assets/sprite_37.png",
    "notes": ""
  },
  {
    "id": 94,
    "name": "Gold Burnt Peanut",
    "rarity": "SPECIAL",
    "image": "assets/sprite_burnt_peanut_gold.png",
    "level": 0,
    "acquired": false,
    "source": "Added editable slot per user request",
    "variantFamily": "Gold",
    "baseName": "Burnt Peanut",
    "category": "user-requested-variant-slot",
    "sortGroup": 9,
    "placeholderArt": true,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gold_Burnt_Peanut_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_burnt_peanut_gold.png",
    "notes": ""
  },
  {
    "id": 95,
    "name": "Galaxy Burnt Peanut",
    "rarity": "SPECIAL",
    "image": "assets/sprite_burnt_peanut_galaxy.png",
    "level": 0,
    "acquired": false,
    "source": "Added editable slot per user request",
    "variantFamily": "Galaxy",
    "baseName": "Burnt Peanut",
    "category": "user-requested-variant-slot",
    "sortGroup": 9,
    "placeholderArt": true,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Galaxy_Burnt_Peanut_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_burnt_peanut_galaxy.png",
    "notes": ""
  },
  {
    "id": 71,
    "name": "Holofoil Burnt Peanut",
    "rarity": "SPECIAL",
    "image": "assets/sprite_burnt_peanut_holofoil.png",
    "level": 0,
    "acquired": false,
    "source": "Added editable slot per user request",
    "variantFamily": "Holofoil",
    "baseName": "Burnt Peanut",
    "category": "user-requested-variant-slot",
    "sortGroup": 9,
    "placeholderArt": true,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Burnt_Peanut_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_burnt_peanut_holofoil.png",
    "notes": ""
  },
  {
    "id": 87,
    "name": "Gem Burnt Peanut",
    "rarity": "SPECIAL",
    "image": "assets/sprite_burnt_peanut_gem.png",
    "level": 0,
    "acquired": false,
    "source": "Added editable slot per user request",
    "variantFamily": "Gem",
    "baseName": "Burnt Peanut",
    "category": "user-requested-variant-slot",
    "sortGroup": 9,
    "placeholderArt": true,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Burnt_Peanut_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_burnt_peanut_gem.png",
    "notes": ""
  },
  {
    "id": 38,
    "name": "Zero Point Sprite",
    "rarity": "MYTHIC",
    "image": "assets/sprite_38.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Base",
    "baseName": "Zero Point",
    "category": "official-sheet",
    "sortGroup": 10,
    "fallbackImage": "assets/sprite_38.png",
    "notes": ""
  },
  {
    "id": 39,
    "name": "Gold Zero Point Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_39.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gold",
    "baseName": "Zero Point",
    "category": "official-sheet",
    "sortGroup": 10,
    "fallbackImage": "assets/sprite_39.png",
    "notes": ""
  },
  {
    "id": 40,
    "name": "Gummy Zero Point Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_40.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gummy",
    "baseName": "Zero Point",
    "category": "official-sheet",
    "sortGroup": 10,
    "fallbackImage": "assets/sprite_40.png",
    "notes": ""
  },
  {
    "id": 41,
    "name": "Galaxy Zero Point Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_41.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Zero Point",
    "category": "official-sheet",
    "sortGroup": 10,
    "fallbackImage": "assets/sprite_41.png",
    "notes": ""
  },
  {
    "id": 72,
    "name": "Holofoil Zero Point Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_38.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Zero Point",
    "category": "holofoil-gem-tracker",
    "sortGroup": 10,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Zero_Point_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_38.png",
    "notes": ""
  },
  {
    "id": 88,
    "name": "Gem Zero Point Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_38.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Zero Point",
    "category": "holofoil-gem-tracker",
    "sortGroup": 10,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Zero_Point_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_38.png",
    "notes": ""
  },
  {
    "id": 42,
    "name": "Fishy Sprite",
    "rarity": "RARE",
    "image": "assets/sprite_42.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Fishy",
    "category": "official-sheet",
    "sortGroup": 11,
    "fallbackImage": "assets/sprite_42.png",
    "notes": ""
  },
  {
    "id": 43,
    "name": "Gold Fishy Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_43.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gold",
    "baseName": "Fishy",
    "category": "official-sheet",
    "sortGroup": 11,
    "fallbackImage": "assets/sprite_43.png",
    "notes": ""
  },
  {
    "id": 44,
    "name": "Gummy Fishy Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_44.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Fishy",
    "category": "official-sheet",
    "sortGroup": 11,
    "fallbackImage": "assets/sprite_44.png",
    "notes": ""
  },
  {
    "id": 45,
    "name": "Galaxy Fishy Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_45.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Fishy",
    "category": "official-sheet",
    "sortGroup": 11,
    "fallbackImage": "assets/sprite_45.png",
    "notes": ""
  },
  {
    "id": 73,
    "name": "Holofoil Fishy Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_42.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Fishy",
    "category": "holofoil-gem-tracker",
    "sortGroup": 11,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Fishy_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_42.png",
    "notes": ""
  },
  {
    "id": 89,
    "name": "Gem Fishy Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_42.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Fishy",
    "category": "holofoil-gem-tracker",
    "sortGroup": 11,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Fishy_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_42.png",
    "notes": ""
  },
  {
    "id": 46,
    "name": "Striker Sprite",
    "rarity": "EPIC",
    "image": "assets/sprite_46.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Striker",
    "category": "official-sheet",
    "sortGroup": 12,
    "fallbackImage": "assets/sprite_46.png",
    "notes": ""
  },
  {
    "id": 47,
    "name": "Gold Striker Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_47.png",
    "level": 1,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Striker",
    "category": "official-sheet",
    "sortGroup": 12,
    "fallbackImage": "assets/sprite_47.png",
    "notes": ""
  },
  {
    "id": 48,
    "name": "Gummy Striker Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_48.png",
    "level": 2,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Striker",
    "category": "official-sheet",
    "sortGroup": 12,
    "fallbackImage": "assets/sprite_48.png",
    "notes": ""
  },
  {
    "id": 49,
    "name": "Galaxy Striker Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_49.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Striker",
    "category": "official-sheet",
    "sortGroup": 12,
    "fallbackImage": "assets/sprite_49.png",
    "notes": ""
  },
  {
    "id": 74,
    "name": "Holofoil Striker Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_46.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Striker",
    "category": "holofoil-gem-tracker",
    "sortGroup": 12,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Striker_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_46.png",
    "notes": ""
  },
  {
    "id": 90,
    "name": "Gem Striker Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_46.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Striker",
    "category": "holofoil-gem-tracker",
    "sortGroup": 12,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Striker_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_46.png",
    "notes": ""
  },
  {
    "id": 50,
    "name": "Aura Sprite",
    "rarity": "EPIC",
    "image": "assets/sprite_50.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Aura",
    "category": "official-sheet",
    "sortGroup": 13,
    "fallbackImage": "assets/sprite_50.png",
    "notes": ""
  },
  {
    "id": 51,
    "name": "Gold Aura Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_51.png",
    "level": 4,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Gold",
    "baseName": "Aura",
    "category": "official-sheet",
    "sortGroup": 13,
    "fallbackImage": "assets/sprite_51.png",
    "notes": ""
  },
  {
    "id": 52,
    "name": "Gummy Aura Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_52.png",
    "level": 1,
    "acquired": true,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Aura",
    "category": "official-sheet",
    "sortGroup": 13,
    "fallbackImage": "assets/sprite_52.png",
    "notes": ""
  },
  {
    "id": 53,
    "name": "Galaxy Aura Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_53.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Aura",
    "category": "official-sheet",
    "sortGroup": 13,
    "fallbackImage": "assets/sprite_53.png",
    "notes": ""
  },
  {
    "id": 75,
    "name": "Holofoil Aura Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_50.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Aura",
    "category": "holofoil-gem-tracker",
    "sortGroup": 13,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Aura_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_50.png",
    "notes": ""
  },
  {
    "id": 91,
    "name": "Gem Aura Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_50.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Aura",
    "category": "holofoil-gem-tracker",
    "sortGroup": 13,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Aura_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_50.png",
    "notes": ""
  },
  {
    "id": 54,
    "name": "Boss Sprite",
    "rarity": "LEGENDARY",
    "image": "assets/sprite_54.png",
    "level": 5,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Base",
    "baseName": "Boss",
    "category": "official-sheet",
    "sortGroup": 14,
    "fallbackImage": "assets/sprite_54.png",
    "notes": ""
  },
  {
    "id": 55,
    "name": "Gold Boss Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_55.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gold",
    "baseName": "Boss",
    "category": "official-sheet",
    "sortGroup": 14,
    "fallbackImage": "assets/sprite_55.png",
    "notes": ""
  },
  {
    "id": 56,
    "name": "Gummy Boss Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_56.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Boss",
    "category": "official-sheet",
    "sortGroup": 14,
    "fallbackImage": "assets/sprite_56.png",
    "notes": ""
  },
  {
    "id": 57,
    "name": "Galaxy Boss Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_57.png",
    "level": 4,
    "acquired": true,
    "source": "screenshot",
    "variantFamily": "Galaxy",
    "baseName": "Boss",
    "category": "official-sheet",
    "sortGroup": 14,
    "fallbackImage": "assets/sprite_57.png",
    "notes": ""
  },
  {
    "id": 76,
    "name": "Holofoil Boss Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_54.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Boss",
    "category": "holofoil-gem-tracker",
    "sortGroup": 14,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Boss_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_54.png",
    "notes": ""
  },
  {
    "id": 92,
    "name": "Gem Boss Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_54.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Boss",
    "category": "holofoil-gem-tracker",
    "sortGroup": 14,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Boss_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_54.png",
    "notes": ""
  },
  {
    "id": 58,
    "name": "Grim Sprite",
    "rarity": "MYTHIC",
    "image": "assets/sprite_58.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Base",
    "baseName": "Grim",
    "category": "official-sheet",
    "sortGroup": 15,
    "fallbackImage": "assets/sprite_58.png",
    "notes": ""
  },
  {
    "id": 59,
    "name": "Gold Grim Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_59.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gold",
    "baseName": "Grim",
    "category": "official-sheet",
    "sortGroup": 15,
    "fallbackImage": "assets/sprite_59.png",
    "notes": ""
  },
  {
    "id": 60,
    "name": "Gummy Grim Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_60.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Gummy",
    "baseName": "Grim",
    "category": "official-sheet",
    "sortGroup": 15,
    "fallbackImage": "assets/sprite_60.png",
    "notes": ""
  },
  {
    "id": 61,
    "name": "Galaxy Grim Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_61.png",
    "level": 0,
    "acquired": false,
    "source": "not acquired / unknown",
    "variantFamily": "Galaxy",
    "baseName": "Grim",
    "category": "official-sheet",
    "sortGroup": 15,
    "fallbackImage": "assets/sprite_61.png",
    "notes": ""
  },
  {
    "id": 77,
    "name": "Holofoil Grim Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_58.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Holofoil",
    "baseName": "Grim",
    "category": "holofoil-gem-tracker",
    "sortGroup": 15,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Holofoil_Grim_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_58.png",
    "notes": ""
  },
  {
    "id": 93,
    "name": "Gem Grim Sprite",
    "rarity": "SPECIAL",
    "image": "assets/sprite_58.png",
    "level": 0,
    "acquired": false,
    "source": "Fandom image URL + local fallback",
    "variantFamily": "Gem",
    "baseName": "Grim",
    "category": "holofoil-gem-tracker",
    "sortGroup": 15,
    "placeholderArt": false,
    "remoteImage": "https://fortnite.fandom.com/wiki/Special:FilePath/Gem_Grim_Sprite_-_Item_-_Fortnite.png",
    "fallbackImage": "assets/sprite_58.png",
    "notes": ""
  }
];
